Fixes race conditions when tracking file syncing
Adds logic to try twice if a sync object gets newly
created and picked up by multiple clients on the same
server. Twice is enough because the second time the
code will receive a completion status from whatever
other process did permorm the operation.

This commit should get rid forever of all exceptions
that appeared as:

CbrainTransitionException: Sync status was changed before lock was acquired.